Update iam.tf latest CA
lablabs/terraform-aws-eks-cluster-autoscaler pull request #15
Opened 2023-08-26 18:35 UTC by ismailyenigul

See 
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws#full-cluster-autoscaler-features-policy-recommended

# Description

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [ ] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

2023-09-15 07:46 UTC, jaygridley requested changes
Change looks good to me. One minor thing, could you please sort actions alphabetically, please?

2023-09-15 12:57 UTC, jaygridley approved these changes

2023-09-15 13:02 UTC, jaygridley commented
@ismailyenigul Could you please fix https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler/actions/runs/6195897654/job/16828593299?pr=15?

2023-11-23 12:30 UTC, Balsir commented
@ismailyenigul Implemented in version [v2.2.0](https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler/releases/tag/v2.2.0)

2025-05-12 06:34 UTC, closed without merging